<?php

use Melios\PageBuilder\Block\Adminhtml\ImageEditor;
use Magento\Framework\Escaper;

/** @var ImageEditor $block */
/** @var Escaper $escaper */

?>

<div class="melios-image-editor-modal" style="display: none" data-config="<?= $escaper->escapeHtmlAttr($block->getConfigJson()) ?>">
    <div class="page-main-actions" data-bind="scope: 'meliosImageEditorActions'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
    <div class="melios-image-editor-wrapper">
        <div id="melios-image-editor-canvas"></div>
        <div id="melios-image-editor" data-bind="scope: 'meliosImageEditor'">
            <!-- ko if: image() -->
                <!-- ko template: getTemplate() --><!-- /ko -->
            <!-- /ko -->
        </div>
    </div>
</div>
